const crypto = require('crypto')

const password1 = "UmxWRFN5QkdUMUlnUmtsQlZDd2dUVVZTUlV0QklFMUZUa2RWUWtGSUlFdEZTRWxFVlZCQlRpQkxSVXhWUVZKSFFVdFZJU0JFUVU0ZwpTMVZCVGxSVlRTQkxUMDVRVlZSRlVpQlpRVTVISUZOQlRrZEJWQ0JQVUNCTlJVMUNWVUZVSUVGSklGTkZUVUZMU1U0Z1IwRk9RVk1LCg=="
const password2 = "VVZWMFZrbEdUbFpTUlVaSlNVVXhSbFJWU2xaUlZsRm5VekJHVFZOVlJrOUpSazVHVkd0R1QxSjVSV2RWTUZaT1ZEQmtRa2xGVWtaVQphMlJDVkdsQ1NsUnJhMmRUTUVaTlUxVkdUd3BKUlVwQ1ZHdGtTRkZSYnowSwo="
const hash = crypto.createHash('sha256').update(password1 + password2).digest('sha');
console.log(hash)
