name: Next.js CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Dependencies for Frontend
      run: |
        sudo apt update
        sudo apt update -y
        cd ui
        npm ci
      
    - name: Build Frontend
      run: |
        cd ui
        npm run build

    - name: Cache Next.js Build
      uses: actions/cache@v4
      with:
        path: ui/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('ui/package-lock.json') }}-${{ hashFiles('ui/**/*.[jt]s', 'ui/**/*.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('ui/package-lock.json') }}

    - name: Install Dependencies for Backend
      run: |
        cd backend/node/server
        npm ci
        npm install --legacy=peer-deps

    - name: Start Backend for Testing
      run: |
        cd backend/node/server
        npm run start

    - name: Run Tests
      run: npm test
